processor:
  group_id: "cybertrace-graph-ingestor-01"
  log_level: "INFO"
  detection_interval: 300  # Run graph detections every 5 minutes

kafka:
  bootstrap_servers: "localhost:9092"

neo4j:
  uri: "bolt://localhost:7687"

input_topics:
  - "apt.events.enriched"
  - "apt.alerts.raw"
