"""
DGA (Domain Generation Algorithm) Classifier for CyberTrace-Graph.

Uses a Random Forest model trained on procedurally generated synthetic
domains to classify whether a given domain name was generated by a DGA
or is a legitimate human-registered domain.

Features extracted from domain names:
- Length and structure metrics
- Shannon entropy (randomness measure)
- Character composition (vowel, consonant, digit ratios)
- Sequential patterns (consecutive consonants/digits)
- Bigram novelty score
"""

import math
import logging
from typing import Optional
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

from junction_nodes.stream_processor.ml_models.data_generator import SyntheticDataGenerator

class DGAClassifier:
    def __init__(self):
        self.model = None
        self.is_trained = False
        self.logger = logging.getLogger(__name__)

    @staticmethod
    def extract_features(domain: str) -> list[float]:
        if not domain:
            return [0.0] * 12

        parts = domain.split('.')
        if len(parts) > 1:
            subdomain = parts[0]
        else:
            subdomain = domain

        if not subdomain:
            return [0.0] * 12

        length = float(len(domain))
        subdomain_length = float(len(subdomain))

        # Entropy
        char_counts = {}
        for c in subdomain:
            char_counts[c] = char_counts.get(c, 0) + 1
        
        entropy = 0.0
        for count in char_counts.values():
            p = count / subdomain_length
            entropy -= p * math.log2(p)

        vowels = set('aeiou')
        consonants = set('bcdfghjklmnpqrstvwxyz')
        digits = set('0123456789')

        vowel_count = 0
        consonant_count = 0
        digit_count = 0
        special_char_count = 0

        max_consecutive_consonants = 0
        current_consecutive_consonants = 0
        max_consecutive_digits = 0
        current_consecutive_digits = 0

        for c in subdomain.lower():
            if c in vowels:
                vowel_count += 1
                current_consecutive_consonants = 0
                current_consecutive_digits = 0
            elif c in consonants:
                consonant_count += 1
                current_consecutive_consonants += 1
                if current_consecutive_consonants > max_consecutive_consonants:
                    max_consecutive_consonants = current_consecutive_consonants
                current_consecutive_digits = 0
            elif c in digits:
                digit_count += 1
                current_consecutive_digits += 1
                if current_consecutive_digits > max_consecutive_digits:
                    max_consecutive_digits = current_consecutive_digits
                current_consecutive_consonants = 0
            else:
                special_char_count += 1
                current_consecutive_consonants = 0
                current_consecutive_digits = 0

        vowel_ratio = vowel_count / subdomain_length
        digit_ratio = digit_count / subdomain_length
        consonant_ratio = consonant_count / subdomain_length
        special_char_ratio = special_char_count / subdomain_length

        unique_char_ratio = len(char_counts) / subdomain_length
        has_hyphen = 1.0 if '-' in subdomain else 0.0

        # n_gram_novelty (bigram novelty)
        if subdomain_length < 2:
            n_gram_novelty = 0.0
        else:
            bigrams = [subdomain[i:i+2] for i in range(len(subdomain)-1)]
            unique_bigrams = len(set(bigrams))
            n_gram_novelty = unique_bigrams / len(bigrams)

        return [
            length,
            subdomain_length,
            entropy,
            vowel_ratio,
            digit_ratio,
            consonant_ratio,
            special_char_ratio,
            float(max_consecutive_consonants),
            float(max_consecutive_digits),
            unique_char_ratio,
            has_hyphen,
            n_gram_novelty
        ]

    def train(self, n_benign: int = 8000, n_dga: int = 8000) -> dict:
        self.logger.info("Generating synthetic data for DGA model training.")
        generator = SyntheticDataGenerator()
        
        # Fallbacks for various potential generator method names
        try:
            benign_domains = generator.generate_benign_domains(n_benign)
            dga_domains = generator.generate_dga_domains(n_dga)
        except AttributeError:
            try:
                benign_domains = generator.generate_benign(n_benign)
                dga_domains = generator.generate_dga(n_dga)
            except AttributeError:
                benign_domains = [generator.generate_benign() for _ in range(n_benign)]
                dga_domains = [generator.generate_dga() for _ in range(n_dga)]
                
        # Clean up to get strings
        benign_domains = [d if isinstance(d, str) else d.get('domain', str(d)) for d in benign_domains]
        dga_domains = [d if isinstance(d, str) else d.get('domain', str(d)) for d in dga_domains]

        X = []
        y = []

        for d in benign_domains:
            X.append(self.extract_features(d))
            y.append(0)

        for d in dga_domains:
            X.append(self.extract_features(d))
            y.append(1)

        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

        self.logger.info("Training RandomForestClassifier...")
        self.model = RandomForestClassifier(n_estimators=100, max_depth=15, random_state=42, n_jobs=-1)
        self.model.fit(X_train, y_train)

        y_pred = self.model.predict(X_test)
        
        metrics = {
            'accuracy': accuracy_score(y_test, y_pred),
            'precision': precision_score(y_test, y_pred),
            'recall': recall_score(y_test, y_pred),
            'f1': f1_score(y_test, y_pred)
        }

        self.logger.info(f"Model training complete. Metrics: {metrics}")
        self.is_trained = True
        return metrics

    def predict(self, domain: str) -> dict:
        if not self.is_trained or self.model is None:
            raise RuntimeError("Model is not trained. Call train() first.")

        features = self.extract_features(domain)
        pred = self.model.predict([features])[0]
        prob = self.model.predict_proba([features])[0]

        is_dga = bool(pred == 1)
        confidence = float(prob[1]) if is_dga else float(prob[0])
        
        feature_keys = [
            'length', 'subdomain_length', 'entropy', 'vowel_ratio',
            'digit_ratio', 'consonant_ratio', 'special_char_ratio',
            'max_consecutive_consonants', 'max_consecutive_digits',
            'unique_char_ratio', 'has_hyphen', 'n_gram_novelty'
        ]
        
        return {
            'domain': domain,
            'is_dga': is_dga,
            'confidence': confidence,
            'features': dict(zip(feature_keys, features))
        }

    def predict_batch(self, domains: list[str]) -> list[dict]:
        if not self.is_trained or self.model is None:
            raise RuntimeError("Model is not trained. Call train() first.")
            
        if not domains:
            return []

        features_list = [self.extract_features(d) for d in domains]
        preds = self.model.predict(features_list)
        probs = self.model.predict_proba(features_list)
        
        feature_keys = [
            'length', 'subdomain_length', 'entropy', 'vowel_ratio',
            'digit_ratio', 'consonant_ratio', 'special_char_ratio',
            'max_consecutive_consonants', 'max_consecutive_digits',
            'unique_char_ratio', 'has_hyphen', 'n_gram_novelty'
        ]

        results = []
        for i, domain in enumerate(domains):
            is_dga = bool(preds[i] == 1)
            confidence = float(probs[i][1]) if is_dga else float(probs[i][0])
            results.append({
                'domain': domain,
                'is_dga': is_dga,
                'confidence': confidence,
                'features': dict(zip(feature_keys, features_list[i]))
            })

        return results
